# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_db_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 401)
        self.button_save_pref = QtWidgets.QPushButton(Form)
        self.button_save_pref.setGeometry(QtCore.QRect(520, 330, 112, 41))
        self.button_save_pref.setObjectName("button_save_pref")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 40, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(350, 110, 141, 16))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 30, 281, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 261, 321))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_dbtype = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.lineEdit_dbtype.setObjectName("lineEdit_dbtype")
        self.horizontalLayout_6.addWidget(self.lineEdit_dbtype)
        self.label_dbtype = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbtype.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dbtype.setObjectName("label_dbtype")
        self.horizontalLayout_6.addWidget(self.label_dbtype)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_dbhost = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dbhost.setObjectName("lineEdit_dbhost")
        self.horizontalLayout_7.addWidget(self.lineEdit_dbhost)
        self.label_dbHost = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbHost.setObjectName("label_dbHost")
        self.horizontalLayout_7.addWidget(self.label_dbHost)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_dbuser = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dbuser.setObjectName("lineEdit_dbuser")
        self.horizontalLayout_8.addWidget(self.lineEdit_dbuser)
        self.label_dbUser = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbUser.setObjectName("label_dbUser")
        self.horizontalLayout_8.addWidget(self.label_dbUser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_dbpass = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dbpass.setObjectName("lineEdit_dbpass")
        self.horizontalLayout_9.addWidget(self.lineEdit_dbpass)
        self.label_dbPass = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbPass.setObjectName("label_dbPass")
        self.horizontalLayout_9.addWidget(self.label_dbPass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_dbbase = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dbbase.setObjectName("lineEdit_dbbase")
        self.horizontalLayout_10.addWidget(self.lineEdit_dbbase)
        self.label_dbBase = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbBase.setObjectName("label_dbBase")
        self.horizontalLayout_10.addWidget(self.label_dbBase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_dbport = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_dbport.setObjectName("lineEdit_dbport")
        self.horizontalLayout_11.addWidget(self.lineEdit_dbport)
        self.label_dbPort = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dbPort.setObjectName("label_dbPort")
        self.horizontalLayout_11.addWidget(self.label_dbPort)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_chose_loadMode = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_chose_loadMode.setObjectName("comboBox_chose_loadMode")
        self.horizontalLayout_2.addWidget(self.comboBox_chose_loadMode)
        self.label_loadMode = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_loadMode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_loadMode.setObjectName("label_loadMode")
        self.horizontalLayout_2.addWidget(self.label_loadMode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(339, 30, 291, 151))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 271, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.open_excel_file = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        self.open_excel_file.setObjectName("open_excel_file")
        self.horizontalLayout_3.addWidget(self.open_excel_file)
        self.excelFileName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.excelFileName.setReadOnly(True)
        self.excelFileName.setObjectName("excelFileName")
        self.horizontalLayout_3.addWidget(self.excelFileName)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 100, 271, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_excel_file_2 = QtWidgets.QToolButton(self.horizontalLayoutWidget_4)
        self.open_excel_file_2.setObjectName("open_excel_file_2")
        self.horizontalLayout_4.addWidget(self.open_excel_file_2)
        self.target_table_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.target_table_name.setReadOnly(True)
        self.target_table_name.setObjectName("target_table_name")
        self.horizontalLayout_4.addWidget(self.target_table_name)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(340, 200, 291, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_checkMode = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_checkMode.setObjectName("checkBox_checkMode")
        self.horizontalLayout.addWidget(self.checkBox_checkMode)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 271, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.open_excel_compare_file = QtWidgets.QToolButton(self.horizontalLayoutWidget_5)
        self.open_excel_compare_file.setObjectName("open_excel_compare_file")
        self.horizontalLayout_5.addWidget(self.open_excel_compare_file)
        self.compare_file = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.compare_file.setReadOnly(True)
        self.compare_file.setObjectName("compare_file")
        self.horizontalLayout_5.addWidget(self.compare_file)
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(170, 10, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(340, 330, 111, 31))
        self.checkBox.setObjectName("checkBox")
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.button_save_pref.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.checkBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Data Base Preferences"))
        self.button_save_pref.setText(_translate("Form", "SAVE"))
        self.label.setText(_translate("Form", "Source excel file name:"))
        self.label_2.setText(_translate("Form", "Target table name:"))
        self.label_dbtype.setText(_translate("Form", "dbtype"))
        self.label_dbHost.setText(_translate("Form", "dbHost"))
        self.label_dbUser.setText(_translate("Form", "dbUser"))
        self.label_dbPass.setText(_translate("Form", "dbPass"))
        self.label_dbBase.setText(_translate("Form", "dbBase"))
        self.label_dbPort.setText(_translate("Form", "dbPort"))
        self.label_loadMode.setText(_translate("Form", "Load Mode"))
        self.open_excel_file.setText(_translate("Form", "..."))
        self.open_excel_file_2.setText(_translate("Form", "..."))
        self.checkBox_checkMode.setText(_translate("Form", "Check mode"))
        self.label_3.setText(_translate("Form", "Check table name:"))
        self.open_excel_compare_file.setText(_translate("Form", "..."))
        self.pushButton.setText(_translate("Form", "Settings"))
        self.checkBox.setText(_translate("Form", "Dictionaty"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
